name: new_wewo
version: 1.0.0+1
publish_to: none
description: new_wewo.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:

  flutter_svg: ^1.1.1+1
  intl:
  sizer: ^2.0.15
  another_flushbar: ^1.10.28
  lottie: ^2.0.0
  cached_network_image: ^3.2.3
  otp_text_field: ^1.1.3
  #network
  
  http: ^0.13.5

  #Firebase
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  sign_in_with_apple: ^3.3.0
  firebase_messaging: ^14.1.1
  flutter_local_notifications: ^9.4.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.3
  google_sign_in: ^5.2.4
  bottom_navy_bar: ^6.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/

# example:
fonts:
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf
      - asset: assets/fonts/Quicksand-Light.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-SemiBold.ttf